//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class interestRate
    {
        public string term { get; set; }
        public Nullable<double> interestRate1 { get; set; }
    }
}
