//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_1.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Text.RegularExpressions;

    public partial class passbook
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public passbook()
        {
            this.SavingsDeposits = new HashSet<SavingsDeposit>();
            this.WithdrawalSlips = new HashSet<WithdrawalSlip>();
        }
    
        public int SavingsBookID { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> OpeningDate { get; set; }
        
        [RegularExpression(@"^[1-9]\d{6,}$", ErrorMessage = "Số tiền gửi ít nhất là 1 triệu đồng")]
        public Nullable<int> InitialDepositAmount { get; set; }
        public Nullable<int> DepositAmount { get; set; }
        public Nullable<double> InterestRate { get; set; }
        public Nullable<int> SavingsType { get; set; }
        public Nullable<bool> IsClosed { get; set; }
    
        public virtual SavingsAccountType SavingsAccountType { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SavingsDeposit> SavingsDeposits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WithdrawalSlip> WithdrawalSlips { get; set; }
    }
}
