//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_1.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Project1DBEntities : DbContext
    {
        public Project1DBEntities()
            : base("name=Project1DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<interestRate> interestRates { get; set; }
        public virtual DbSet<passbook> passbooks { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<user> users { get; set; }
    
        public virtual int DepositMoney(Nullable<int> user_id, Nullable<int> passbook_id, Nullable<double> amount)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var passbook_idParameter = passbook_id.HasValue ?
                new ObjectParameter("passbook_id", passbook_id) :
                new ObjectParameter("passbook_id", typeof(int));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DepositMoney", user_idParameter, passbook_idParameter, amountParameter);
        }
    }
}
