//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavingsAccountType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SavingsAccountType()
        {
            this.passbooks = new HashSet<passbook>();
        }
    
        public int SavingsTypeID { get; set; }
        public string AccountTypeName { get; set; }
        public Nullable<double> InterestRate { get; set; }
        public Nullable<int> Term { get; set; }
        public Nullable<int> WithdrawalDays { get; set; }
        public Nullable<int> MinimumDeposit { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> AllowsAdditionalDeposits { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<passbook> passbooks { get; set; }
    }
}
