//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WithdrawalSlip
    {
        public int WithdrawalID { get; set; }
        public Nullable<int> SavingsBookID { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> WithdrawalAmount { get; set; }
        public Nullable<System.DateTime> WithdrawalDate { get; set; }
    
        public virtual passbook passbook { get; set; }
        public virtual user user { get; set; }
    }
}
